### ISSUE TITLE
Plugin deadlocks

### ISSUE THREAD

**Issue by nicity** [evenaglia/Non-Dairy-Soy-Plugin#20]
"ApplicationImpl pooled thread 70" prio=4 tid=139a88800 nid=0x13ff52000 waiting on condition [13ff50000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <6fb57c710> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:156)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:811)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:969)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1281)
	at java.util.concurrent.locks.ReentrantReadWriteLock$ReadLock.lockInterruptibly(ReentrantReadWriteLock.java:722)
	at com.intellij.openapi.application.impl.ApplicationImpl.c(ApplicationImpl.java:913)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:886)
	at com.intellij.webcore.libraries.ScriptingLibraryManager.getAllLibraryFiles(ScriptingLibraryManager.java:329)
	at com.intellij.webcore.libraries.ScriptingIndexableSetContributor.getLibraryFiles(ScriptingIndexableSetContributor.java:45)
	at com.intellij.webcore.libraries.ScriptingIndexableSetContributor.getAdditionalProjectRootsToIndex(ScriptingIndexableSetContributor.java:37)
	at com.intellij.util.indexing.IndexableSetContributor.getProjectRootsToIndex(IndexableSetContributor.java:51)
	at com.intellij.util.indexing.FileBasedIndexImpl.iterateIndexableFiles(FileBasedIndexImpl.java:2598)
	at com.intellij.util.indexing.FileBasedIndexImpl.projectIndexableFiles(FileBasedIndexImpl.java:1093)
	at com.intellij.util.indexing.FileBasedIndexImpl$14.convert(FileBasedIndexImpl.java:969)
	at com.intellij.util.indexing.FileBasedIndexImpl$14.convert(FileBasedIndexImpl.java:946)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:919)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:992)
	at com.intellij.util.indexing.FileBasedIndexImpl.getContainingFiles(FileBasedIndexImpl.java:876)
	at com.intellij.psi.search.FilenameIndex.getVirtualFilesByName(FilenameIndex.java:90)
	at com.intellij.psi.search.FilenameIndex.getAllFilesByExt(FilenameIndex.java:192)
	at com.intellij.psi.search.FilenameIndex.getAllFilesByExt(FilenameIndex.java:176)
	at net.venaglia.nondairy.soylang.cache.SoyCacheUpdater.queryNeededFiles(SoyCacheUpdater.java:102)
	at com.intellij.openapi.project.CacheUpdateSession.<init>(CacheUpdateSession.java:50)
	at com.intellij.openapi.project.CacheUpdateRunner.b(CacheUpdateRunner.java:72)
	at com.intellij.openapi.project.CacheUpdateRunner.a(CacheUpdateRunner.java:65)
	at com.intellij.openapi.project.CacheUpdateRunner.performInDumbMode(CacheUpdateRunner.java:235)
	at com.intellij.openapi.project.DumbServiceImpl$8.run(DumbServiceImpl.java:416)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:152)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:452)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:402)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:137)
	at com.intellij.openapi.project.DumbServiceImpl.a(DumbServiceImpl.java:407)
	at com.intellij.openapi.project.DumbServiceImpl.access$1100(DumbServiceImpl.java:52)
	at com.intellij.openapi.project.DumbServiceImpl$7.run(DumbServiceImpl.java:389)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:563)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:152)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:452)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:402)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:137)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:126)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:400)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:695)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:56)

**Comment by nicity** [comment]
Relevant IDEA ticket https://youtrack.jetbrains.com/issue/IDEA-141786
